// Global using directives

global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.IO;
global using System.Linq;
global using System.Reflection;
global using System.Text;
global using System.Threading;
global using AdvancedWorldGen.Base;
global using AdvancedWorldGen.BetterVanillaWorldGen;
global using AdvancedWorldGen.BetterVanillaWorldGen.DesertStuff;
global using AdvancedWorldGen.BetterVanillaWorldGen.DungeonStuff;
global using AdvancedWorldGen.BetterVanillaWorldGen.FloatingSky;
global using AdvancedWorldGen.BetterVanillaWorldGen.Interface;
global using AdvancedWorldGen.BetterVanillaWorldGen.Jungle;
global using AdvancedWorldGen.BetterVanillaWorldGen.MicroBiomesStuff;
global using AdvancedWorldGen.CustomSized;
global using AdvancedWorldGen.Helper;
global using AdvancedWorldGen.Helper.Accessors;
global using AdvancedWorldGen.SpecialOptions;
global using AdvancedWorldGen.SpecialOptions.Halloween;
global using AdvancedWorldGen.SpecialOptions.Halloween.Worldgen;
global using AdvancedWorldGen.SpecialOptions.Snow;
global using AdvancedWorldGen.UI;
global using AdvancedWorldGen.UI.InputUI;
global using AdvancedWorldGen.UI.InputUI.List;
global using AdvancedWorldGen.UI.InputUI.Number;
global using Humanizer;
global using Humanizer.Localisation;
global using Microsoft.Xna.Framework;
global using Microsoft.Xna.Framework.Graphics;
global using Microsoft.Xna.Framework.Input;
global using Mono.Cecil.Cil;
global using MonoMod.Cil;
global using MonoMod.RuntimeDetour.HookGen;
global using Newtonsoft.Json;
global using Newtonsoft.Json.Linq;
global using ReLogic.Content;
global using ReLogic.OS;
global using Terraria;
global using Terraria.Audio;
global using Terraria.Chat;
global using Terraria.DataStructures;
global using Terraria.GameContent;
global using Terraria.GameContent.Achievements;
global using Terraria.GameContent.Biomes;
global using Terraria.GameContent.Biomes.Desert;
global using Terraria.GameContent.Creative;
global using Terraria.GameContent.Events;
global using Terraria.GameContent.Generation;
global using Terraria.GameContent.UI.Elements;
global using Terraria.GameContent.UI.States;
global using Terraria.GameInput;
global using Terraria.ID;
global using Terraria.IO;
global using Terraria.Localization;
global using Terraria.Map;
global using Terraria.ModLoader;
global using Terraria.ModLoader.Config;
global using Terraria.ModLoader.IO;
global using Terraria.ModLoader.UI;
global using Terraria.UI;
global using Terraria.Utilities;
global using Terraria.WorldBuilding;
global using ILPlayer = IL.Terraria.Player;
global using ILProjectile = IL.Terraria.Projectile;
global using ILWorldGen = IL.Terraria.WorldGen;
global using OnDesertDescription = On.Terraria.GameContent.Biomes.Desert.DesertDescription;
global using OnDesertHive = On.Terraria.GameContent.Biomes.Desert.DesertHive;
global using OnGenPass = On.Terraria.WorldBuilding.GenPass;
global using OnMain = On.Terraria.Main;
global using OnNPC = On.Terraria.NPC;
global using OnPlayer = On.Terraria.Player;
global using OnUIWorldCreation = On.Terraria.GameContent.UI.States.UIWorldCreation;
global using OnUIWorldListItem = On.Terraria.GameContent.UI.Elements.UIWorldListItem;
global using OnUIWorldLoad = On.Terraria.GameContent.UI.States.UIWorldLoad;
global using OnUserInterface = On.Terraria.UI.UserInterface;
global using OnWorldFile = On.Terraria.IO.WorldFile;
global using OnWorldFileData = On.Terraria.IO.WorldFileData;
global using OnWorldGen = On.Terraria.WorldGen;
global using OnWorldGenerator = On.Terraria.WorldBuilding.WorldGenerator;